root: ./docs

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  architecture: core-concepts/architecture.md
  quantum: core-concepts/quantum-sass.md
  crisis: core-concepts/crisis-management.md
  examples: examples/processing-transactions.md
  api: api-reference/jape-ai.md
  contribute: contributing/development-guide.md
  faq: resources/faq.md
